# Generated by Django 2.2 on 2019-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190426_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
