# Generated by Django 2.2 on 2019-04-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_document_annotated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='labels',
            field=models.ManyToManyField(blank=True, to='app.Label'),
        ),
    ]
