# Generated by Django 2.2 on 2019-04-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190426_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='documentimport',
            name='project',
        ),
        migrations.RemoveField(
            model_name='label',
            name='project',
        ),
        migrations.AddField(
            model_name='documentimport',
            name='description',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='documentimport',
            name='filename',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
